baseURL = "https://joonasmmp.github.io/"
title = "PJMM - Englannin materiaalia"
author = "PJMM"
languageCode = "fi"
DefaultContentLanguage = "fi"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = false

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-735JW4B10W"

# Disqus Comment System
#disqusShortname = ""

[params]
# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-gray-800"

#Site description
description = "Blonde theme for Hugo."

# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = true

# Number of tags to be displayed.
tagsLimit = 20

# Dark mode by default : dark
# Light mode by default : light
darkmode = "light"

  [params.post]
    # Show thumbnails
    thumbnail = true

    # Disable the "NO IMAGE" image.
    noimage = false

    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "lg:h-55"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "lg:w-auto"

    # Number of characters in description
    description = "300"

    # Mainsections
    mainSections = ["post"]

  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["palkki","category", "tags", "recent"]

[menu]

  [[menu.main]]
  name = "Etusivu"
  url = "/"
  identifier = "home"
  weight = 1

[[menu.main]]
  name = "Kurssimateriaalit"
  url = "/kurssit/"
  identifier = "kurssit"
  weight = 2
  hasChildren = true

[[menu.main]]
  name = "ENA 01 - Kielitaito & vuorovaikutus"
  url = "/kurssit/ena01tehtavat/"
  identifier = "ena01tehtavat"
  weight = 1
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 02 - Globaali kieli"
  url = "/kurssit/ena02tehtavat/"
  identifier = "ena02tehtavat"
  weight = 2
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 03 - Kieli & kulttuuri"
  url = "/kurssit/ena03tehtavat/"
  identifier = "ena03tehtavat"
  weight = 3
  parent = "kurssit"
  
 [[menu.main]]
  name = "ENA 04 - Yhteiskunta & vaikuttaminen"
  url = "/kurssit/ena04tehtavat/"
  identifier = "ena04tehtavat"
  weight = 4
  parent = "kurssit"
  
 [[menu.main]]
  name = "ENA 05 - Tiede & tulevaisuus"
  url = "/kurssit/ena05tehtavat/"
  identifier = "ena05tehtavat"
  weight = 5
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 06 - Jatko-opinnot & työelämä"
  url = "/kurssit/ena06tehtavat/"
  identifier = "ena06tehtavat"
  weight = 6
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 07 - Ympäristö & kestävä elämäntapa"
  url = "/kurssit/ena07tehtavat/"
  identifier = "ena07tehtavat"
  weight = 7
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 08 - Suullinen viestintä"
  url = "/kurssit/ena08tehtavat/"
  identifier = "ena08tehtavat"
  weight = 8
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 09 - Abikurssi"
  url = "/kurssit/ena09tehtavat/"
  identifier = "ena09tehtavat"
  weight = 9
  parent = "kurssit"
  
[[menu.main]]
  name = "Ylioppilaskoe"
  url = "/yo-kokeet/"
  identifier = "YO-kokeet"
  weight = 3
  hasChildren = true
  
[[menu.main]]
  name = "Kuuntelukoe"
  url = "/yo-kokeet/kuuntelukoe/"
  identifier = "kuuntelukoe"
  weight = 1
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Luetunymmärtäminen"
  url = "/yo-kokeet/luetunymmartaminen/"
  identifier = "luetunymmartäminen"
  weight = 2
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Rakenneosio"
  url = "/yo-kokeet/rakenneosio/"
  identifier = "rakenneosio"
  weight = 3
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Kirjoitelma"
  url = "/yo-kokeet/kirjoitelma/"
  identifier = "kirjoitelma fa-fw"
  weight = 4
  parent = "YO-kokeet"

[[menu.main]]
  name = "Muuta"
  url = "/muuta/"
  identifier = "muuta"
  weight = 6

  [[menu.main]]
  name = "Podcast-suositukset"
  url = "/yo-kokeet/podcast/"
  identifier = "podcast"
  weight = 1
  parent = "muuta"

[[menu.main]]
  name = "Phrase bank"
  url = "/yo-kokeet/phrasebank/"
  identifier = "phrasebank"
  weight = 1
  parent = "muuta"


[[menu.main]]
  name = "Tietoja"
  url = "/about/"
  identifier = "about"
  weight = 7


[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true