baseURL = "https://joonasmmp.github.io/"
title = "PJMM - Englannin materiaalia"
author = "PJMM"
languageCode = "fi"
DefaultContentLanguage = "fi"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = false

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-735JW4B10W"

# Disqus Comment System
#disqusShortname = ""

[params]
# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-gray-800"

#Site description
description = "Blonde theme for Hugo."

# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = true

# Number of tags to be displayed.
tagsLimit = 20

# Dark mode by default : dark
# Light mode by default : light
darkmode = "light"

  [params.post]
    # Show thumbnails
    thumbnail = true

    # Disable the "NO IMAGE" image.
    noimage = true

    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "lg:h-44"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "lg:w-auto"

    # Number of characters in description
    description = "130"

  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["search", "archive", "category", "tags", "recent"]

[menu]

  [[menu.main]]
  name = "Etusivu"
  url = "/"
  identifier = "home"
  Pre  = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "Kurssimateriaalit"
  url = "/kurssit/"
  identifier = "kurssit"
  Pre = "fas fa-pencil-alt"
  weight = 2
  hasChildren = true

[[menu.main]]
  name = "ENA 01"
  url = "/kurssit/ena01tehtavat/"
  identifier = "ena01tehtavat"
  Pre = "fas fa-globe-europe fa-fw"
  weight = 1
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 02"
  url = "/kurssit/ena02tehtavat/"
  identifier = "ena02tehtavat"
  Pre = "fas fa-wifi fa-fw"
  weight = 2
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 03"
  url = "/kurssit/ena03tehtavat/"
  identifier = "ena03tehtavat"
  Pre = "fas fa-paint-brush fa-fw"
  weight = 3
  parent = "kurssit"
  
 [[menu.main]]
  name = "ENA 04"
  url = "/kurssit/ena04tehtavat/"
  identifier = "ena04tehtavat"
  Pre = "fas fa-balance-scale fa-fw"
  weight = 4
  parent = "kurssit"
  
 [[menu.main]]
  name = "ENA 05"
  url = "/kurssit/ena05tehtavat/"
  identifier = "ena05tehtavat"
  Pre = "fas fa-flask fa-fw"
  weight = 5
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 06"
  url = "/kurssit/ena06tehtavat/"
  identifier = "ena06tehtavat"
  Pre = "fas fa-user-graduate fa-fw"
  weight = 6
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 07"
  url = "/kurssit/ena07tehtavat/"
  identifier = "ena07tehtavat"
  Pre = "fab fa-pagelines fa-fw"
  weight = 7
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 08"
  url = "/kurssit/ena08tehtavat/"
  identifier = "ena08tehtavat"
  Pre = "far fa-comments fa-fw"
  weight = 8
  parent = "kurssit"
  
[[menu.main]]
  name = "ENA 09"
  url = "/kurssit/ena09tehtavat/"
  identifier = "ena09tehtavat"
  Pre = "fas fa-italic fa-fw"
  weight = 9
  parent = "kurssit"
  
[[menu.main]]
  name = "YO-kokeet"
  url = "/yo-kokeet/"
  identifier = "YO-kokeet"
  Pre = "fa fa-puzzle-piece"
  weight = 3
  hasChildren = true
  
[[menu.main]]
  name = "Kuuntelukoe"
  url = "/yo-kokeet/kuuntelukoe/"
  identifier = "kuuntelukoe"
  Pre = "fa fa-headphones fa-fw"
  weight = 1
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Luetunymmärtäminen"
  url = "/yo-kokeet/luetunymmartaminen/"
  identifier = "luetunymmartäminen"
  Pre = "fas fa-book-reader fa-fw"
  weight = 2
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Rakenneosio"
  url = "/yo-kokeet/rakenneosio/"
  identifier = "rakenneosio"
  Pre = "fas fa-clipboard-list fa-fw"
  weight = 3
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Kirjoitelma"
  url = "/yo-kokeet/kirjoitelma/"
  identifier = "kirjoitelma fa-fw"
  Pre = "far fa-keyboard"
  weight = 4
  parent = "YO-kokeet"

[[menu.main]]
  name = "Tietoja"
  url = "/about/"
  pre = "fas fa-question"
  identifier = "about"
  weight = 6

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true