baseurl = ""
languageCode = "en-us"
title = "PJMM - Englannin materiaalia"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 5
googleAnalytics = "G-735JW4B10W"
pluralizeListTitles = false
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

[params]
  # Sets the meta tag description
  description          = "PJMM"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "PJMM"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/blog/"
  mainSections = ["blog"]

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = false
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # set to show or to hide categories in the sidebar
  showSidebarCategories = true

  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["default"]
  customJS             = ["default"]

  # options for highlight.js (version, additional languages, and theme)
  disable_highlight = false # set to true to disable Highlight
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "css"]
  highlightjsTheme = "github"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

  [params.staticman.recaptcha]
    sitekey = "SITE_KEY"
    secret  = "ENCRYPTED_SECRET"

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = "PJMM"

  paragraph = "Jep"

  about     = "asdsadsadsasdasda"

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 3

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item

[[menu.main]]
  name = "Etusivu"
  url = "/"
  identifier = "home"
  Pre  = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "Tehtävät"
  url = "/tehtavat/"
  identifier = "Tehtävät"
  Pre = "fas fa-pencil-alt"
  weight = 2
  hasChildren = true

[[menu.main]]
  name = "ENA 01"
  url = "/tehtavat/ena01tehtavat/"
  identifier = "ena01tehtavat"
  Pre = "fas fa-globe-europe"
  weight = 1
  parent = "Tehtävät"
  
[[menu.main]]
  name = "ENA 02"
  url = "/tehtavat/ena02tehtavat/"
  identifier = "ena02tehtavat"
  Pre = "fas fa-wifi"
  weight = 2
  parent = "Tehtävät"
  
[[menu.main]]
  name = "ENA 03"
  url = "/tehtavat/ena03tehtavat/"
  identifier = "ena03tehtavat"
  Pre = "fas fa-paint-brush"
  weight = 3
  parent = "Tehtävät"
  
 [[menu.main]]
  name = "ENA 04"
  url = "/tehtavat/ena04tehtavat/"
  identifier = "ena04tehtavat"
  Pre = "fas fa-balance-scale"
  weight = 4
  parent = "Tehtävät"
  
 [[menu.main]]
  name = "ENA 05"
  url = "/tehtavat/ena05tehtavat/"
  identifier = "ena05tehtavat"
  Pre = "fas fa-flask"
  weight = 5
  parent = "Tehtävät"
  
[[menu.main]]
  name = "ENA 06"
  url = "/tehtavat/ena06tehtavat/"
  identifier = "ena06tehtavat"
  Pre = "fas fa-user-graduate"
  weight = 6
  parent = "Tehtävät"
  
[[menu.main]]
  name = "ENA 07"
  url = "/tehtavat/ena07tehtavat/"
  identifier = "ena07tehtavat"
  Pre = "fab fa-pagelines"
  weight = 7
  parent = "Tehtävät"
  
[[menu.main]]
  name = "ENA 08"
  url = "/tehtavat/ena08tehtavat/"
  identifier = "ena08tehtavat"
  Pre = "far fa-comments"
  weight = 8
  parent = "Tehtävät"
  
[[menu.main]]
  name = "ENA 09"
  url = "/tehtavat/ena09tehtavat/"
  identifier = "ena09tehtavat"
  Pre = "fas fa-italic"
  weight = 9
  parent = "Tehtävät"
  
[[menu.main]]
  name = "YO-kokeet"
  url = "/yo-kokeet/"
  identifier = "YO-kokeet"
  Pre = "fa fa-puzzle-piece"
  weight = 3
  hasChildren = true
  
[[menu.main]]
  name = "Kuuntelukoe"
  url = "/yo-kokeet/kuuntelukoe/"
  identifier = "kuuntelukoe"
  Pre = "fa fa-headphones"
  weight = 1
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Luetunymmärtäminen"
  url = "/yo-kokeet/luetunymmartaminen/"
  identifier = "luetunymmartäminen"
  Pre = "fas fa-book-reader"
  weight = 2
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Rakenneosio"
  url = "/yo-kokeet/rakenneosio/"
  identifier = "rakenneosio"
  Pre = "fas fa-clipboard-list"
  weight = 3
  parent = "YO-kokeet"
  
  [[menu.main]]
  name = "Kirjoitelma"
  url = "/yo-kokeet/kirjoitelma/"
  identifier = "kirjoitelma"
  Pre = "far fa-keyboard"
  weight = 4
  parent = "YO-kokeet"

[[menu.main]]
  name = "Tietoja"
  url = "/about/"
  pre = "fas fa-question"
  identifier = "about"
  weight = 6
